name: majelis_adventure
description: "A premium outdoor rental app for Majelis Adventure."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0 # Pastikan versi SDK Flutter kamu cocok dengan ini

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 
  image_picker: ^1.1.2

# KONFIGURASI LOGO (Penting: Sejajar dengan dev_dependencies, bukan di dalamnya)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/img/majelis.png" # Lokasi logo barumu
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/majelis.png