// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_ab3rpM2o-v4EK6AdNkyKzAqIQk0m00',
    appId: '1:443174553074:web:21cbaf4bdde08cca8dd76b',
    messagingSenderId: '443174553074',
    projectId: 'majelis-rental',
    authDomain: 'majelis-rental.firebaseapp.com',
    storageBucket: 'majelis-rental.firebasestorage.app',
    measurementId: 'G-138DQPZCP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9PqWjSzMJhVcdUjiLg2RwXdV4EK-fFuM',
    appId: '1:443174553074:android:ce495110616f500d8dd76b',
    messagingSenderId: '443174553074',
    projectId: 'majelis-rental',
    storageBucket: 'majelis-rental.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaeuKPsYxwutnkmb0eaI40cag5ud5IThE',
    appId: '1:443174553074:ios:5a8762937e674fcd8dd76b',
    messagingSenderId: '443174553074',
    projectId: 'majelis-rental',
    storageBucket: 'majelis-rental.firebasestorage.app',
    androidClientId: '443174553074-2p8e3h7gvfu5qum43kiu162ssm1q1rl3.apps.googleusercontent.com',
    iosClientId: '443174553074-cuvnnlco5e7c8eglmciitvo69jp1o4rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalOutdoorMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaeuKPsYxwutnkmb0eaI40cag5ud5IThE',
    appId: '1:443174553074:ios:5a8762937e674fcd8dd76b',
    messagingSenderId: '443174553074',
    projectId: 'majelis-rental',
    storageBucket: 'majelis-rental.firebasestorage.app',
    androidClientId: '443174553074-2p8e3h7gvfu5qum43kiu162ssm1q1rl3.apps.googleusercontent.com',
    iosClientId: '443174553074-cuvnnlco5e7c8eglmciitvo69jp1o4rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalOutdoorMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp_ab3rpM2o-v4EK6AdNkyKzAqIQk0m00',
    appId: '1:443174553074:web:21cbaf4bdde08cca8dd76b',
    messagingSenderId: '443174553074',
    projectId: 'majelis-rental',
    authDomain: 'majelis-rental.firebaseapp.com',
    storageBucket: 'majelis-rental.firebasestorage.app',
    measurementId: 'G-138DQPZCP0',
  );
}
